### ISSUE TITLE
React e Angular 2 estão fazendo o que era feito com JavaScript antes da separação de responsabilidades do HTML e JS!

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/help-me-change-my-mind#1]
Alguém havia comentado sobre isso no Slack do grupo [ABC-Dev](https://github.com/abc-dev) e por isso gostaria de abrir essa discussão para incrementar nosso conhecimento sobre o assunto.

Antigamente se fazia HTML, CSS e JS tudo em um arquivo só. Com o tempo veio a separação de responsabilidades e o HTML foi para um arquivo, o CSS para outro e o JS para outro. Depois disseram que não era mais para se utilizar eventos diretamente no HTML, mas para usar algo novo e maravilhoso que eram os `eventListeners`. Em seguida disseram para não gerar HTML com JavaScrtipt e hoje em dia vemos que isso voltou.

O Angular 1 (falo do Angular pela popularidade) já devolveu no meio do HTML os `onclick="function()"`, da vida vide [`ng-click`](https://docs.angularjs.org/api/ng/directive/ngClick).

Agora, com o conceito de componentes gerados via JS, algo tem cheirado mal para o desenvolvimento Front End, isso aqui:

**Angular 2**
```
@Component({
  selector: 'hero-app',
  template: `
    <h1>Tour of Heroes</h1>
    <hero-app-main [hero]=hero></hero-app-main>`,
  styles: ['h1 { font-weight: normal; }'],
  directives: [HeroAppMainComponent]
})
```
[link](https://angular.io/docs/ts/latest/guide/component-styles.html)

HTML, CSS e JS, tudo no mesmo local.

**React**
```
// main.js
var React = require('react');
var ReactDOM = require('react-dom');

ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('example')
);
```

JavaScript cuspindo HTML (também tem o CSS no meio em outros exemplos).

[link](https://facebook.github.io/react/docs/getting-started.html)

Antigamente disseram para não deixar a responsabilidade de escrever HTML/CSS para o JavaScript e hoje vemos isso acontecendo de novo. Será que, num futuro próximo, isso não pode ser visto como má prática?

Qual seria a defesa para usar essa forma de se trabalhar?

**Comment by karlprieb** [comment]
Componentização. Sanidade na componentização? https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.edw26jrva

Buuut, temos esse que defende a componentização sem a estilização no mesmo "package". https://medium.com/front-end-developers/stop-styling-react-components-with-javascript-8b4a7ec96eea#.1qpyt9dok

E para uma leitura final que fala sobre React e explica HTML no JS https://edgecoders.com/what-exactly-is-react-js-d04ebfb5c610#.cvrn4dv5u

**Comment by woliveiras** [comment]
Shooooow @karlprieb

**Comment by AbraaoAlves** [comment]
> Não se pode levar algo em consideração sem entender o porque da coisas, do contrário suas decisões apenas seguirão o rumo da maré.

Vivi essa transição de separar/juntar Html/Css/JS e também tive as mesmas perguntas.
A separação entre essas tecnologias foi um passo muito importante na época em que foi disseminada e ainda faz muito sentido na maioria dos sites e alguns webapps atuais.

Hoje as necessidades mudaram, as ferramentas, as equipes e os webapps já não são mais tão simples. Componentes são uma realidade e cada dia que passa essa abordagem tem se mostrado eficiente nos webapps modernos, não apenas no resultado final mas também durante o desenvolvimento. 
Acredito que o fato de integrar as tecnologias html/css/js ([WebPack](http://webpack.github.io/)), veio da necessidade de entregar componentes cada vez mais independentes e escaláveis, que facilitaram o desenvolvimento dos grandes SinglePageApps. veja: [angular style guide: LIFT principle](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#application-structure-lift-principle)  

Agora, imaginemos no que a abordagem de webcomponents poderia beneficiar os devs na primeira década desse milênio? Nem haviam SPAs! 

Outro exemplo:
Imagine você apresentando um modelo de programação elaborado na na década de 50 (FunctionalProgramming) para devs que viviam o BOOM da evolução nos processadores dos anos 2000?! [Detalhe: [FunctionalProgramming is hot today](http://www.wired.com/2015/09/whatsapp-serves-900-million-users-50-engineers/)].

> Muita coisa mudou e talvez ainda aproveitemos muita mais do passado. Mas só obteremos bons resultados se realmente tivermos aprendido algo nessa caminhada de mudanças.

Se você é muito novo e não viveu isso tudo, converse com programadores mais velhos, ouça as histórias e tente aprender um pouco com isso. Não sou tão velho, mas sempre gostei de ouvir histórias, como a de colega que fazia ajax no IE5, antes do próprio termo ajax. 

Então lembre-se: 
**_FullStackWebDeveloper não é WebMasterBlaster_**. Ou será que é?

**Comment by woliveiras** [comment]
Show ein @AbraaoAlves. Valeu pelos pontos.

O termo FullStack é outra coisa que tem dado o que falar nas comunidades... kkkkk

**Comment by sombriks** [comment]
templateUrl ainda existe. E funciona. 
Mistura tudo num artefato só quem quer.

**Comment by karlprieb** [comment]
Vale lembrar que templates js também são HTML por JS né. Handlebars, Mustache, Jade, etc são implementaçoes de html no DOM a partir de js.

**Comment by fdaciuk** [comment]
Os links que o @karlprieb postou já esclarecem praticamente tudo, mas em resumo:

Se você vai trabalhar com websites, não use Angular ou React ou qualquer outro framework que tenha sua própria view. HTML estático, ou gerado via servidor continua sendo a melhor solução. **Para websites.**

Ao criar uma aplicação, onde tudo é mais dinâmico, e a precupação com SEO é menor (não vou entrar muito nesse assunto, senão o post vai ficar muito grande), pode ser o caso de você precisar de uma ferramenta como Angular ou React para ajudar a estruturar a aplicação.

Vou falar do React, pois é o que eu tenho mais contato: o que você usa dentro do React não é "HTML dentro JS". Sim, parece muito à primeira vista, e você não delimita esse código com strings. Isso é JSX. E não é delimitado com strings, porque não são strings. Não é esse código que vai para produção.

Você **sempre** vai usar uma ferramenta que vai converter esse código em JSX para JS puro, que nada mais são que funções. O que era:

```jsx
ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('example')
);
```

Vai virar:

```js
ReactDOM.render(
  ReactDOM.createElement('h1', null, 'Hello, world!'),
  document.getElementById('example')
);
```

Perceba que isso nada mais é que uma simples função =)

## Então por que usar JSX? Não dá pra usar só a função?

Porque o que ele vai gerar, no final, é um nó do DOM. HTML.

Usando JSX, você tem a visão final do componente, mas no seu código de desenvolvimento. Dá uma olhada nesse outro exemplo:

```jsx
ReactDOM.render(
  <section className='main-section'>
    <header className='main-header'>
      <h1 className='main-title'>Hello World!</h1>
    </header>
  </section>,
  document.getElementById('example')
);
```

Claramente você consegue ver que eu tenho uma tag `section`, com uma classe `main-section`, dentro dele, um `header`, com a classe `main-header`, e, dentro dele, um `h1`, com a classe `main-title`.

A estrutura do seu componente fica muito clara.

Mas, e se você usasse funções no lugar do JSX, como ficaria?

```js
ReactDOM.render(
  React.createElement('section', { className: 'main-section' },  
    React.createElement('header', { className: 'main-header' },
      React.createElement('h1', { className: 'main-title' })
    )
  ),
  document.getElementById('example')
);
```

Isso com apenas 3 tags e uma única propriedade em cada tag. Percebe a diferença na leitura do código? Essa é a grande vantagem do JSX! Ele te permite, enquanto você desenvolve seu componente, ter a visualização final de como ele ficará no DOM!

E ainda que você coloque cada componente em uma variável para não ficar tudo aninhado, olha só como não fica tão claro o que você quer fazer:

```js
const h1 = React.createElement('h1', { className: 'main-title' });
const header = React.createElement('header', { className: 'main-header' }, h1);
const section = React.createElement('section', { className: 'main-section' },  header);

ReactDOM.render(
  section,
  document.getElementById('example')
);
```

Ou seja: ainda que você tente modularizar, você precisa ler "de baixo para cima", pois a variável do H1 vai  entro do HEADER, então ela precisa ser criada primeiro. Compare com o código em JSX e tire suas próprias conclusões =)

Um outro ponto é a questão **performance.**. O Angular (ao menos na versão 1), usa _string replacement_ para parsear o código dos templates. Me corrijam se eu estiver errado, mas para gerar uma lista com vários itens, por exemplo, ele toca no DOM várias vezes. 

E todos sabemos o quão lento o DOM é.

E também sabemos que, fazer as coisas somente via JS, é muito mais rápido, muito mais performático.

E essa é a grande sacada do React: além da facilidade em componentizar e compor seus componentes, reaproveitando o máximo de código possível, o único momento da sua aplicação inteira que você precisa interagir com o DOM, é quando você usa o `ReactDOM.render()`.

A sacada de usar um DOM Virtual, e, antes de atualizar o DOM real, fazer um diff para saber exatamente o que precisa ser alterado, faz uma grande diferença.

Enfim, performance é um outro assunto. A ideia era só exemplificar um pouco sobre o JSX, e que isso não é "HTML dentro do JS" =)

**Comment by woliveiras** [comment]
@fdaciuk, gerar o HTML pelo JS é mais performático então mano? 

=O

Ai fechou o assunto pra mim!

Só se tiver mais alguém que queira continuar a discussão que deixo aberto a issue. kkkk

**Comment by fdaciuk** [comment]
Mais rápido **que** ficar tocando no DOM a todo momento.

O que eu quis dizer é que, ao invés de ficar atualizando nós do DOM o tempo todo, se vc criar a sua estrutura HTML (para o que você precisa atualizar) e jogar tudo de uma vez no DOM, esse processo se torna, com certeza, muito mais performático.

Mas a estrutura inicial, se já vier montada no primeiro request a partir do servidor, é muito melhor. Melhor para o usuário, melhor se você precisar de SEO para o projeto.

E nesse ponto o React ganha mais um ponto, porque você consegue fazer com ele um pré-render do lado do servidor com o código que ele geraria no frontend, para o primeiro load.

O servidor envia esse HTML semi pronto no padrão que o React precisa para gerar o Virtual DOM =)

**Comment by woliveiras** [comment]
Putz, maneiro mano!

**Comment by roberthlima** [comment]
Eu iria estudar Angular JS, mas depois dessa irei estudar ReactJS :D

**Comment by woliveiras** [comment]
\o/
